{{- if .Values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.storageClass.name }}"
  labels:
    {{- include "p3.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClass.default | quote }}
provisioner: {{ .Values.provisionerName }}
parameters:
  basePath: {{ .Values.storageClass.basePath | quote }}
  pathTemplate: {{ .Values.storageClass.pathTemplate | quote }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}
